### ISSUE TITLE
Create Spectrum class

### ISSUE THREAD

**Issue by jgriss** [spectra-cluster/spectra-cluster-2#1]
## Features

  * Bin according to Comet paper
  * Store peaks as binary
  * Store intensities as integers (see MSFragger)
  * Create unique id for future reference to the "outside" world
  * Add hashing functions
    * Need to explore different options here

**Comment by ypriverol** [comment]
Here the paper of comet https://onlinelibrary.wiley.com/doi/full/10.1002/pmic.201200439

**Comment by jgriss** [comment]
This is an interesting discussion about classes for BitVectors:
https://stackoverflow.com/questions/3040864/java-sparse-bit-vector

The CERN libraries already helped me speed up several parts of the code quite a bit.

**Comment by ypriverol** [comment]
Here the paper that describes the method. https://link.springer.com/article/10.1007/s13361-015-1179-x

**Comment by jgriss** [comment]
@ypriverol 
Maybe we should follow the original approach and represent a spectrum and a cluster by the same object?

**Comment by ypriverol** [comment]
Should we create a class for the Cluster? @jgriss
