### ISSUE TITLE
Error in test

### ISSUE THREAD

**Issue by ypriverol** [spectra-cluster/spectra-cluster-2#102]
@jgriss in my local the following test is falling: 
```
Results :

Failed tests:   testMspWriting(org.spectra.cluster.io.result.MspWriterTest): expected:<Name: [+42.011EVQLVETGGGLIQPGGS]LR/2> but was:<Name: [AARPPLL]LR/2>
```

**Comment by jgriss** [comment]
Hi @ypriverol,

On my machine the test works fine. Also, in the latest run of the CI system ([line 7147](https://github.com/spectra-cluster/spectra-cluster-2/runs/1048849732?check_suite_focus=true#step:4:7147)) this test worked fine.

Can you tell me where the test failed?

Thanks a lot!

**Comment by ypriverol** [comment]
This is the line failing: 

https://github.com/spectra-cluster/spectra-cluster-2/blob/253a6e301a145c2f89fe4bbb3cfea2788fbd068e/src/test/java/org/spectra/cluster/io/result/MspWriterTest.java#L99

**Comment by jgriss** [comment]
I saw where in *the code* but not on *which system*.

GitHub run worked and the test also works on my machine. Is this (still currently) failing on your machine?
