### ISSUE TITLE
Test storing peaks in HashSet

### ISSUE THREAD

**Issue by jgriss** [spectra-cluster/spectra-cluster-2#61]
The idea is that every peak is hashed based on its bin. Next to the array, peaks can be additional stored in a HashSet which should speed up the search for shared peaks.

This replaces #59 since a bit-vector would not scale to high-resolution data and will no be efficient since the vast majority of bits will always be 0 (and there is no scarce implementation available).

**Comment by jgriss** [comment]
After all changes, this implementation is twice as fast as the current one in "develop"

**Comment by ypriverol** [comment]
This is amaizing @jgriss . I will review the PR soon !!!
